project:
  type: website
website:
  title: "Übersicht"
  favicon: logos/svlog.png
  cookie-consent: 
    lang: de
    type: express
    style: simple
    prefs-text: Cookie-Einstellungen
  navbar:
    logo: "/logos/sv_log_weiss.png"
  sidebar: false
  page-footer:
    center: 
      - href: recht/impressum.qmd
    right:
      - href: recht/datenschutz.qmd
    left: |
      [![](/logos/datev_foerder.png){width=50%}
    border: true
format:
  html:
    page-layout: full
    theme: theme.scss
    toc: true
    toc-location: left
    citation: 
      title: "datenkompetent - Beispielhafte Lehrformate und -strategien für die Data Literacy Education an deutschen Hochschulen"
      editor: 
        - Henning Koch
        - Sam Sievers
      license: CC BY-SA
link-external-newwindow: true      
editor: source
lang: de
